### ISSUE TITLE
Include the option to add alfresco-share-services with the yo alfresco:amp-add-common command

### ISSUE THREAD

**Issue by douglascrp** [binduwavell/generator-alfresco#127]
When you need to work with datalists, you have to include the alfresco-share-services dependency into the repo side of the project, so I think it would be useful to have the option to "automate" it by including alfresco-share-services as an option for amp-add-common.

This is the dependency

```
<dependency>
      <groupId>org.alfresco</groupId>
      <artifactId>alfresco-share-services</artifactId>
      <version>5.1.e</version>
      <type>amp</type>
</dependency>
```

**Comment by binduwavell** [comment]
Thanks for the suggestion.

**Comment by vprince1** [comment]
SDK 2.2.0 installs alfresco-share-services automatically.

**Comment by douglascrp** [comment]
@vprince1 I read that somewhere, but it doesn't work for me, and as you can see in the following link, I'm not alone
https://github.com/Alfresco/alfresco-sdk/issues/382
I think what you said is true, but only for AIO projects. Not for the repo though.

**Comment by binduwavell** [comment]
@douglascrp since the yeoman project is completely based on AIO and as far as we can tell this is working I'm going to close this issue. If I've misunderstood, please feel free to re-open.

Just to be clear, adding stuff to the amp-add-common sub-generator is really easy, so the push back here is not about adding something but about adding something we think is not needed.
